
# This file contains all of the valid CMD fields. This was taken from the rsk-powhsm source code.


'''

[INS_SIGN = 0x02,
INS_GET_PUBLIC_KEY = 0x04,
RSK_IS_ONBOARD = 0x06,
RSK_MODE_CMD = 0x43,
INS_ADVANCE = 0x10,
INS_ADVANCE_PARAMS = 0x11,
INS_GET_STATE = 0x20,
INS_RESET_STATE = 0x21,
INS_UPD_ANCESTOR = 0x30,
INS_ATTESTATION = 0x50,
INS_HEARTBEAT = 0x60,
INS_EXIT = 0xff]
'''

INS_SIGN = 0x02
INS_GET_PUBLIC_KEY = 0x04
RSK_IS_ONBOARD = 0x06
RSK_MODE_CMD = 0x43
INS_ADVANCE = 0x10
INS_ADVANCE_PARAMS = 0x11
INS_GET_STATE = 0x20
INS_RESET_STATE = 0x21
INS_UPD_ANCESTOR = 0x30
INS_ATTESTATION = 0x50
INS_HEARTBEAT = 0x60
INS_EXIT = 0xff

# All valid instructions in a list...

all_instructions = [INS_SIGN,
	INS_GET_PUBLIC_KEY,
	RSK_IS_ONBOARD,
	RSK_MODE_CMD,
	INS_ADVANCE,
	INS_ADVANCE_PARAMS,
	INS_GET_STATE,
	INS_RESET_STATE,
	INS_UPD_ANCESTOR,
	INS_ATTESTATION,
	INS_HEARTBEAT,
	INS_EXIT]

